-- Privilegios

-- Privilegios sobre la cuenta 1

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO panfleto954, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO panfleto954, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO panfleto954, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO panfleto954, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO panfleto954, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO panfleto954, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO panfleto954, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO panfleto954, panfleto952, panfleto953;

-- Privilegios sobre la cuenta 2

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO panfleto954, panfleto951, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO panfleto954, panfleto951, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO panfleto954, panfleto951, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO panfleto954, panfleto951, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO panfleto954, panfleto951, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO panfleto954, panfleto951, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO panfleto954, panfleto951, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO panfleto954, panfleto951, panfleto953;

-- Privilegios sobre la cuenta 3

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO panfleto954, panfleto952, panfleto951;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO panfleto954, panfleto952, panfleto951;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO panfleto954, panfleto952, panfleto951;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO panfleto954, panfleto952, panfleto951;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO panfleto954, panfleto952, panfleto951;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO panfleto954, panfleto952, panfleto951;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO panfleto954, panfleto952, panfleto951;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO panfleto954, panfleto952, panfleto951;

-- Privilegios sobre la cuenta 4

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO panfleto951, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO panfleto951, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO panfleto951, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO panfleto951, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO panfleto951, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO panfleto951, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO panfleto951, panfleto952, panfleto953;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO panfleto951, panfleto952, panfleto953;